# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05b4a1f53e5b186795041937876e8b82190264f2ab79b1ff0b5d30e72a9faadb998ba348c5f2c8efc066401e2ea69f323bac375d7ce75e40581471626ad34dcb

test:
  secret_key_base: 012100be4d9dd56abfda3dce2f900bd68811e82b05aeaa52a2e5574c0eb699fe864bbced2cff1f9b7ae53ee9e9d15163697f7eedc6befc53b68319f54d85dfd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
